matrix:
    include:
      - language: node_js
        node_js:
        - '8.9.4'
        branches:
            only:
            - dev
        cache:
            directories:
            - node_modules
        script:
        - npm run lint
