export const getProdutos = state => state.produtos;
export const getProduto = state => state.produto;
export const getAnaliseConteudo = state => state.analiseConteudo;
export const getPlanilhaParecer = state => state.planilhaParecer;
export const getProdutosSecundarios = state => state.produtosSecundarios;
export const getPlanilhaSelecionados = state => state.planilhaSelecionados;
export const getAnaliseConteudoSecundario = state => state.analiseConteudoSecundario;
export const getPlanilhaSecundario = state => state.planilhaSecundario;
export const getConsolidacao = state => state.consolidacao;
