export const SET_PRODUTOS = 'SET_PRODUTOS';
export const SET_PRODUTO = 'SET_PRODUTO';
export const SET_ANALISE_CONTEUDO = 'SET_ANALISE_CONTEUDO';
export const SET_PLANILHA_PARECER = 'SET_PLANILHA_PARECER';
export const SET_PRODUTOS_SECUNDARIOS = 'SET_PRODUTOS_SECUNDARIOS';
